title = "Kydan's Blog"
baseURL = "https://kydrogen.github.io/"
languageCode = "en-us"

theme = "PaperMod"
pagination.pagerSize = 5

[params]
mainSections = ["posts"]
sortOrder = "asc"

[params.footer]
  text = "Pantera School Project"